"""Syntax gate over every piece of JavaScript the firmware serves from a raw string.

WHY THIS EXISTS
    The C++ compiler never parses the contents of a raw string literal. Roughly
    ~1.7 MiB of first-party JavaScript therefore reaches this gate with nothing
    else having checked it is even syntactically valid. (Reaches the gate, not
    "ships": about 1 MB of that is WebPage_Games.h, behind
    ENABLE_WEB_GAME_MAZE=0 on this board -- which is the point, not a caveat.)
    A missing brace
    compiles, links, flashes, and fails on the board. components/hardwareone/
    WebPage_Games.h carries a hand-written window.onerror handler for precisely
    this reason -- its own comment says a JS syntax error otherwise shows up as
    a silent black screen.

    It gets worse where the JS sits behind a build flag. WebPage_Settings.h
    holds script under `#if ENABLE_HTTPS` and under `#if ENABLE_NEOPIXEL`; on a
    board that disables those, the preprocessor discards the block and nothing
    in the toolchain has ever looked at it. This gate does not care which board
    you built -- it reads the source.

WHAT A GREEN RUN DOES NOT MEAN
    - It is a SYNTAX gate, not a semantic one. It cannot tell that
      WebPage_Maps.h references LOD_MAJOR_ROAD, a constant that only exists
      after streamMapsPageLodZoomConstants() in WebPage_Maps.cpp injects it.
      Delete that C++ function and this stays green while the map breaks.
    - JavaScript assembled from ordinary (non-raw) C++ string literals
      (WebPage_Dashboard.h, the window.hw runtime in WebServer_Utils.cpp, the
      sensor web headers) is covered by the CONCATENATED-LITERAL classes below,
      via extract_js.concat_regions / fragment_js. Two regions are structurally
      unparseable from source (runtime-assembled values); they are named in
      extract_js.CONCAT_KNOWN_UNPARSEABLE and a tripwire asserts each still
      fails, so the skip list cannot rot into a silent coverage hole.
    - WebPage_DarkRoom.h is excluded by name in extract_js.WALK_EXCLUDE_NAMES:
      vendored MPL-2.0 code generated by tools/build_darkroom_header.py and
      never hand-edited, so gating it would mean a wall of noise every time the
      pinned upstream moves.

Run from the repository root:

    python3 -m unittest discover -s tools/webui/tests -t .
"""

from __future__ import annotations

import json
import pathlib
import tempfile
import unittest

from tools.webui import extract_js
from tools.webui.js_engine import JS_ENGINE, run_js

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
CHECKER = REPO_ROOT / "tools" / "webui" / "harness" / "syntax_check.js"

# A walk that silently matched nothing would pass vacuously, so the count has a
# floor. Measured today: 36 files with raw-string blocks, 78 regions. The floor
# sits well below that so ordinary churn does not trip it, while a collapse to
# near-zero -- a renamed directory, a broken glob, an over-eager exclusion --
# fails loudly.
MINIMUM_REGIONS = 60


@unittest.skipUnless(
    JS_ENGINE, "a JavaScript engine (node/deno/bun/qjs/jsc/osascript) is required"
)
class EmbeddedJsSyntaxTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.temporary = tempfile.TemporaryDirectory()
        work = pathlib.Path(cls.temporary.name)

        cls.regions: list[tuple[str, pathlib.Path, int]] = []
        cls.extraction_errors: list[str] = []
        manifest_lines: list[str] = []

        for source in extract_js.walk_sources():
            try:
                if not extract_js.extract_blocks(source, require=False):
                    continue
                found = extract_js.joined_regions(source)
            except extract_js.ExtractionError as exc:
                # An extractor that cannot read a file is a failure in its own
                # right: it silently removes that file from coverage.
                cls.extraction_errors.append(str(exc))
                continue
            for region in found:
                target = work / f"region_{len(manifest_lines):03d}.js"
                target.write_text(region.text, encoding="utf-8")
                cls.regions.append((region.name, source, region.first_line))
                manifest_lines.append(
                    json.dumps({"name": region.name, "file": str(target)})
                )

        manifest = work / "manifest.jsonl"
        manifest.write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")
        # One engine invocation for the whole tree; the parse itself is cheap.
        cls.result = run_js(CHECKER, [str(manifest)])
        cls.stdout_lines = cls.result.stdout.splitlines()

    @classmethod
    def tearDownClass(cls) -> None:
        cls.temporary.cleanup()

    def test_extraction_reached_every_source(self) -> None:
        self.assertEqual(
            [], self.extraction_errors,
            "the extractor raised on files that do contain raw-string blocks; "
            "those files are silently uncovered until this is fixed",
        )

    def test_enough_regions_were_found(self) -> None:
        self.assertGreaterEqual(
            len(self.regions), MINIMUM_REGIONS,
            f"only {len(self.regions)} JS regions found across the tree, expected "
            f"at least {MINIMUM_REGIONS}. A walk that matches nothing passes every "
            "other assertion in this file, so this floor is the real guard.",
        )

    def test_engine_did_not_crash(self) -> None:
        self.assertEqual(
            0, self.result.returncode,
            f"JS engine {JS_ENGINE} exited {self.result.returncode}\n"
            f"stderr:\n{self.result.stderr}",
        )

    def test_every_region_parses(self) -> None:
        verdicts = [l for l in self.stdout_lines if l.startswith("SYNTAX_RESULT")]
        self.assertEqual(
            1, len(verdicts),
            f"expected exactly one SYNTAX_RESULT line, got {len(verdicts)}\n"
            f"stdout tail:\n{chr(10).join(self.stdout_lines[-10:])}\n"
            f"stderr:\n{self.result.stderr}",
        )

        by_name = {name: (src, line) for name, src, line in self.regions}
        problems = []
        for entry in self.stdout_lines:
            if not entry.startswith("SYNTAX FAIL "):
                continue
            body = entry[len("SYNTAX FAIL "):]
            name, _, message = body.partition(" ")
            source, first_line = by_name.get(name, (pathlib.Path(name), 0))
            try:
                shown = source.relative_to(REPO_ROOT)
            except ValueError:
                shown = source
            problems.append(f"{shown}:{first_line}  {message}")

        self.assertEqual(
            "SYNTAX_RESULT PASS", verdicts[0],
            "embedded JavaScript failed to parse:\n  " + "\n  ".join(problems),
        )

    def test_all_regions_were_checked(self) -> None:
        checked = sum(
            1 for l in self.stdout_lines
            if l.startswith("SYNTAX OK ") or l.startswith("SYNTAX FAIL ")
        )
        self.assertEqual(
            len(self.regions), checked,
            f"handed the checker {len(self.regions)} regions but it reported on "
            f"{checked}; the manifest and the run disagree",
        )


# (name, source file, anchor, replacement) -- each introduces one syntax error.
GATE_MUTATIONS = [
    (
        "unbalanced brace",
        "WebPage_LLM.h",
        "  function scheduleBeat(ms) {",
        "  function scheduleBeat(ms) { if (1) {",
    ),
    (
        "malformed object literal",
        "WebPage_LLM.h",
        "  var BEAT_FAST = 1000, BEAT_SLOW = 5000;",
        "  var BEAT_FAST = 1000, BEAT_SLOW = 5000; var bad = { a: 1 b: 2 };",
    ),
    (
        # Legal inside a FunctionBody, a SyntaxError in a classic <script>. The
        # primary AsyncFunction parse accepts both; the script-goal parse is the
        # only thing that rejects them.
        #
        # These must sit at TRUE top level. Nearly all of this page lives inside
        # an IIFE, where `return` is legal in every goal -- an earlier version of
        # this mutation anchored inside it and was silently not caught.
        "top-level return (legal in a function body, not in a script)",
        "WebPage_LLM.h",
        "<script>\n(function(){",
        "<script>\nreturn;\n(function(){",
    ),
    (
        "top-level await (legal in an async body, not in a classic script)",
        "WebPage_LLM.h",
        "<script>\n(function(){",
        "<script>\nvar probe = await null;\n(function(){",
    ),
    (
        # The one that justifies the whole gate. WebPage_Maps.h is wrapped in
        # `#if ENABLE_MAPS` (:9 to :2975) and ENABLE_MAPS is 0 in the current
        # build config, so the preprocessor discards the entire file and no
        # compiler on this machine has ever seen this line. A green firmware
        # build says nothing whatsoever about it.
        #
        # This anchor was previously in WebPage_Settings.h and was WRONG: the
        # `#if ENABLE_ESPNOW` there closes at :710, one line BEFORE the raw
        # string opens at :711, so that block compiles on both boards and the
        # suite had no mutation in discarded code at all. Rewording the comment
        # would not have fixed it -- the anchor had to move.
        "JS inside a block this board does not compile",
        "WebPage_Maps.h",
        "let zoom = 10;",
        "let zoom = 10 10;",
    ),
]


@unittest.skipUnless(
    JS_ENGINE, "a JavaScript engine (node/deno/bun/qjs/jsc/osascript) is required"
)
class SyntaxGateDetectsBreakageTests(unittest.TestCase):
    """The gate is nearly all negative assertions, so prove it can say no.

    Without this, a checker that silently parsed an empty string would pass
    every other test in this file.
    """

    @classmethod
    def setUpClass(cls) -> None:
        cls.temporary = tempfile.TemporaryDirectory()
        cls.work = pathlib.Path(cls.temporary.name)

    @classmethod
    def tearDownClass(cls) -> None:
        cls.temporary.cleanup()

    def _check_mutated(self, filename: str, old: str, new: str) -> tuple[str, list[str]]:
        source = extract_js.COMPONENTS / filename
        text = source.read_text(encoding="utf-8")
        self.assertEqual(
            1, text.count(old),
            f"mutation anchor appears {text.count(old)} times in {filename}; "
            "it must appear exactly once. Update the anchor, do not delete the case.",
        )
        # Mutate a COPY. No repository file is ever written by this suite.
        copy = self.work / filename
        copy.write_text(text.replace(old, new, 1), encoding="utf-8")

        lines = []
        for index, region in enumerate(extract_js.joined_regions(copy)):
            target = self.work / f"r{index}.js"
            target.write_text(region.text, encoding="utf-8")
            lines.append(json.dumps({"name": region.name, "file": str(target)}))
        manifest = self.work / "manifest.jsonl"
        manifest.write_text("\n".join(lines) + "\n", encoding="utf-8")

        out = run_js(CHECKER, [str(manifest)]).stdout.splitlines()
        verdicts = [l for l in out if l.startswith("SYNTAX_RESULT")]
        return (verdicts[0] if verdicts else "(no verdict)"),\
               [l for l in out if l.startswith("SYNTAX FAIL")]

    def test_broken_javascript_is_rejected(self) -> None:
        for name, filename, old, new in GATE_MUTATIONS:
            with self.subTest(mutation=name):
                verdict, failures = self._check_mutated(filename, old, new)
                self.assertTrue(
                    verdict.startswith("SYNTAX_RESULT FAIL"),
                    f"introducing a syntax error ({name}) did not fail the gate: "
                    f"verdict was {verdict!r}",
                )
                self.assertTrue(
                    failures,
                    f"gate reported FAIL for {name} but named no region",
                )


if __name__ == "__main__":
    unittest.main()


# ===========================================================================
# Concatenated-literal gate (wave-3 corpus). Same shape as the raw-string
# gate above: extract, parse once, then prove the path can say no.
# ===========================================================================

MINIMUM_CONCAT_REGIONS = 30
MINIMUM_CONCAT_BYTES = 100_000


def _concat_manifest(work: pathlib.Path):
    """(regions, manifest_lines) for the concat + fragment corpus."""
    regions: list[tuple[str, pathlib.Path, int]] = []
    lines: list[str] = []
    for name in extract_js.CONCAT_SOURCES:
        source = extract_js.COMPONENTS / name
        for region in extract_js.concat_regions(source):
            if region.name in extract_js.CONCAT_KNOWN_UNPARSEABLE:
                continue
            target = work / f"concat_{len(lines):03d}.js"
            target.write_text(region.text, encoding="utf-8")
            regions.append((region.name, source, region.first_line))
            lines.append(json.dumps({"name": region.name, "file": str(target)}))
    for name in extract_js.FRAGMENT_SOURCES:
        source = extract_js.COMPONENTS / name
        body = extract_js.fragment_js(source)
        if not body.strip():
            continue
        target = work / f"concat_{len(lines):03d}.js"
        target.write_text(body, encoding="utf-8")
        regions.append((f"{name}#fragment", source, 1))
        lines.append(json.dumps({"name": f"{name}#fragment", "file": str(target)}))
    return regions, lines


@unittest.skipUnless(
    JS_ENGINE, "a JavaScript engine (node/deno/bun/qjs/jsc/osascript) is required"
)
class ConcatJsSyntaxTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.temporary = tempfile.TemporaryDirectory()
        work = pathlib.Path(cls.temporary.name)
        cls.regions, lines = _concat_manifest(work)
        manifest = work / "manifest.jsonl"
        manifest.write_text("\n".join(lines) + "\n", encoding="utf-8")
        cls.result = run_js(CHECKER, [str(manifest)])
        cls.stdout_lines = cls.result.stdout.splitlines()

    @classmethod
    def tearDownClass(cls) -> None:
        cls.temporary.cleanup()

    def test_enough_concat_coverage(self) -> None:
        total = 0
        for name in extract_js.CONCAT_SOURCES:
            for region in extract_js.concat_regions(extract_js.COMPONENTS / name):
                if region.name not in extract_js.CONCAT_KNOWN_UNPARSEABLE:
                    total += len(region.text)
        for name in extract_js.FRAGMENT_SOURCES:
            total += len(extract_js.fragment_js(extract_js.COMPONENTS / name))
        self.assertGreaterEqual(len(self.regions), MINIMUM_CONCAT_REGIONS)
        self.assertGreaterEqual(
            total, MINIMUM_CONCAT_BYTES,
            "concatenated-literal coverage collapsed; a lexer or roster "
            "regression can silently un-cover this corpus",
        )

    def test_engine_did_not_crash(self) -> None:
        self.assertEqual(0, self.result.returncode, self.result.stderr)

    def test_every_concat_region_parses(self) -> None:
        verdicts = [l for l in self.stdout_lines if l.startswith("SYNTAX_RESULT")]
        self.assertEqual(1, len(verdicts), self.stdout_lines[-10:])
        by_name = {name: (src, line) for name, src, line in self.regions}
        problems = []
        for entry in self.stdout_lines:
            if entry.startswith("SYNTAX FAIL "):
                body = entry[len("SYNTAX FAIL "):]
                name, _, message = body.partition(" ")
                source, first_line = by_name.get(name, (pathlib.Path(name), 0))
                problems.append(f"{source}:{first_line}  {message}")
        self.assertEqual(
            "SYNTAX_RESULT PASS", verdicts[0],
            "concatenated-literal JavaScript failed to parse:\n  " + "\n  ".join(problems),
        )

    def test_known_unparseable_regions_still_fail(self) -> None:
        """Tripwire: every skip-list entry must STILL fail to parse.

        If one starts parsing, the code changed and the entry must be removed
        -- otherwise the skip list quietly becomes a coverage hole.
        """
        work = pathlib.Path(self.temporary.name)
        lines = []
        for name in extract_js.CONCAT_KNOWN_UNPARSEABLE:
            filename = name.split("#")[0]
            for region in extract_js.concat_regions(extract_js.COMPONENTS / filename):
                if region.name == name:
                    target = work / f"skip_{len(lines)}.js"
                    target.write_text(region.text, encoding="utf-8")
                    lines.append(json.dumps({"name": name, "file": str(target)}))
        self.assertEqual(
            len(extract_js.CONCAT_KNOWN_UNPARSEABLE), len(lines),
            "a CONCAT_KNOWN_UNPARSEABLE entry names a region that no longer "
            "exists; remove or update the entry",
        )
        manifest = work / "skips.jsonl"
        manifest.write_text("\n".join(lines) + "\n", encoding="utf-8")
        out = run_js(CHECKER, [str(manifest)]).stdout.splitlines()
        fails = [l for l in out if l.startswith("SYNTAX FAIL ")]
        self.assertEqual(
            len(lines), len(fails),
            "a skip-listed region now PARSES; its CONCAT_KNOWN_UNPARSEABLE "
            "entry is stale and must be removed so the region joins coverage",
        )


CONCAT_MUTATIONS = [
    (
        "broken JS inside an ordinary quoted literal (concat path)",
        "WebPage_Dashboard.h",
        '"window.Dash.openNotifEditor=function(){"',
        '"window.Dash.openNotifEditor=function(){{"',
    ),
    (
        # Board-dark on non-XIAO lanes: ENABLE_CAMERA_SENSOR=0 there, so no
        # compiler ever preprocesses this line on those boards.
        "broken JS in a per-board concat file",
        "System_Camera_DVP_Web.h",
        "hw.setText(stats, 'Camera not enabled (use Open Camera button)')",
        "hw.setText(stats,, 'Camera not enabled (use Open Camera button)')",
    ),
    (
        "broken JS in a fragment file (stream-literal path)",
        "i2csensor_ds3231_web.h",
        "bind('btn-rtc-start','openrtc');",
        "bind('btn-rtc-start',,'openrtc');",
    ),
]


@unittest.skipUnless(
    JS_ENGINE, "a JavaScript engine (node/deno/bun/qjs/jsc/osascript) is required"
)
class ConcatGateDetectsBreakageTests(unittest.TestCase):
    """Prove the NEW extraction paths can say no, mutation by mutation."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.temporary = tempfile.TemporaryDirectory()
        cls.work = pathlib.Path(cls.temporary.name)

    @classmethod
    def tearDownClass(cls) -> None:
        cls.temporary.cleanup()

    def test_broken_javascript_is_rejected(self) -> None:
        for name, filename, old, new in CONCAT_MUTATIONS:
            with self.subTest(mutation=name):
                source = extract_js.COMPONENTS / filename
                text = source.read_text(encoding="utf-8")
                self.assertEqual(1, text.count(old),
                                 f"anchor not unique in {filename}")
                copy = self.work / filename
                copy.write_text(text.replace(old, new, 1), encoding="utf-8")

                lines = []
                if filename in extract_js.FRAGMENT_SOURCES:
                    body = extract_js.fragment_js(copy)
                    target = self.work / "frag.js"
                    target.write_text(body, encoding="utf-8")
                    lines.append(json.dumps({"name": "frag", "file": str(target)}))
                else:
                    for idx, region in enumerate(extract_js.concat_regions(copy)):
                        if region.name in extract_js.CONCAT_KNOWN_UNPARSEABLE:
                            continue
                        target = self.work / f"m{idx}.js"
                        target.write_text(region.text, encoding="utf-8")
                        lines.append(json.dumps({"name": region.name, "file": str(target)}))
                manifest = self.work / "mmanifest.jsonl"
                manifest.write_text("\n".join(lines) + "\n", encoding="utf-8")
                out = run_js(CHECKER, [str(manifest)]).stdout.splitlines()
                verdicts = [l for l in out if l.startswith("SYNTAX_RESULT")]
                self.assertTrue(
                    verdicts and verdicts[0].startswith("SYNTAX_RESULT FAIL"),
                    f"mutation ({name}) was not caught: {verdicts!r}",
                )
