(function(){
  var G=(0,eval)('this'),checked=0,clock=0,rafCalls=0,cancelled=[];
  function noop(){}
  G.window=G;G.addEventListener=noop;
  G.document={getElementById:function(){return null;},addEventListener:noop};
  G.performance={now:function(){return clock++;}};
  G.cancelAnimationFrame=function(id){cancelled.push(id);};
  G.requestAnimationFrame=function(fn){rafCalls++;return rafCalls;};
  G._pt=function(name,fn){return fn();};
  (0,eval)(slurp('assets/games/src/20-browser-profile.js'));
  function check(name,okay){if(!okay)throw Error(name);checked++;__out('PASS '+name);}
  var samples=[9,1,3,5];
  var summary=G.caveProfileSummary(samples);
  check('median averages middle pair without mutating samples',summary.medianMs===4 && samples.join(',')==='9,1,3,5');
  check('p95 uses nearest rank',summary.p95Ms===9 && summary.samples===4);
  check('odd median uses middle sample',G.caveProfileSummary([7,3,5]).medianMs===5);
  check('empty result reports unavailable timings',G.caveProfileSummary([]).medianMs===null && G.caveProfileSummary([]).samples===0);
  var oldDate=Date.now,oldRandom=Math.random,oldPt=G._pt,seen=[];
  var job={frozenTime:2000000000000,randomSeed:1234567,renderMs:[],stages:{}};
  G.drawCaveVisibilityFixtures=function(){seen.push([Date.now(),Math.random(),Math.random()]);G._pt('outer',function(){G._pt('inner',noop);});};
  G.caveProfileRender(job,true);G.caveProfileRender(job,true);
  check('every sampled render gets the same frozen clock and seeded random sequence',JSON.stringify(seen[0])===JSON.stringify(seen[1]) && seen[0][0]===2000000000000);
  check('render restores native clock random and timing wrapper before yielding',Date.now===oldDate && Math.random===oldRandom && G._pt===oldPt);
  check('inclusive stage timings keep parent and child separately',job.stages.outer.length===2 && job.stages.inner.length===2 && job.stages.outer[0]>job.stages.inner[0]);
  check('render command samples recorded once per measured frame',job.renderMs.length===2 && job.renderMs[0]>0);
  G.caveProfileRender(job,false);
  check('warmups do not pollute measured sample counts',job.renderMs.length===2 && job.stages.outer.length===2);
  G.drawCaveVisibilityFixtures=function(){throw Error('injected draw failure');};
  var failed=false;try{G.caveProfileRender(job,true);}catch(e){failed=e.message==='injected draw failure';}
  check('failed render propagates error and restores all temporarily replaced globals',failed && Date.now===oldDate && Math.random===oldRandom && G._pt===oldPt);
  check('failed render is not counted as a successful sample',job.renderMs.length===2);
  var resumed=0;
  G._caveBrowserProfile={raf:17,resume:function(value){if(value===null)resumed++;}};
  G.cancelCaveBrowserProfile('fixture changed');
  check('cancel removes pending animation frame and resumes pending wait',cancelled[0]===17 && resumed===1 && G._caveBrowserProfile.raf===0);
  check('cancel records reason and clears resolver',G._caveBrowserProfile.cancelReason==='fixture changed' && G._caveBrowserProfile.resume===null);
  G.cancelCaveBrowserProfile('cancel again');
  check('repeated cancellation does not double resume or cancel stale callbacks',resumed===1 && cancelled.length===1);
  G._caveBrowserProfile=null;G.cancelCaveBrowserProfile();
  check('cancel without active profile is safe',cancelled.length===1);
  G.canvas={width:1,height:1};var readbacks=0;
  G.ctx={getImageData:function(){readbacks++;return{data:new Uint8Array([12,34,56,255])};}};
  var sig=G.caveProfileContentSignature();
  check('content signature records full RGBA bytes and readback algorithm',sig.bytes===4 && sig.algorithm==='fnv1a32-rgba' && sig.hash.length===8 && readbacks===1);
  check('content signature is deterministic',G.caveProfileContentSignature().hash===sig.hash);
  check('signature reports all twelve spatial tiles from the same readback',sig.tiles.length===12 && sig.tileColumns===4 && sig.tileRows===3 && sig.tiles.reduce(function(n,t){return n+t.bytes;},0)===4);
  var priorReadbacks=readbacks,skipped=G.caveProfileOptionalSignature(false);
  check('pixel verification disabled performs no main-canvas readback',skipped.skipped===true && skipped.reason.indexOf('disabled')>=0 && readbacks===priorReadbacks);
  var verified=G.caveProfileOptionalSignature(true);
  check('pixel verification only reads canvas when explicitly enabled',readbacks===priorReadbacks+1 && verified.hash===sig.hash);
  G.floorMesh={id:'original'};G.WORLD_SEED=12345;
  G.ambientParticles=[{real:true}];G.exploredCells=new Uint8Array([1,0,1]);G.minimapCanvas={real:true};G.minimapDirty=false;
  G.drawMinimap=function(){};G.drawMinimap._fogCanvas={realFog:true};G._lastExploredUpdate=123;
  G._lightGrid=new Float32Array([0.3,0.4]);G._lightGridLastScale=0.3;G._lightGridLastCamGX=7;G._lightGridLastCamGY=8;G._lightGridFrameCount=21;
  G._surfaceFloorLightBake=new Float32Array([0.2,0.6]);G._surfaceFloorLightMesh=G.floorMesh;
  G._surfaceFloorLightScale=0.4;G._surfaceFloorLightStats={bakeMs:2};
  var surfaceBake=G._surfaceFloorLightBake,surfaceStats=G._surfaceFloorLightStats;
  G.settings={showFPS:true};G._fpsSmooth=42;G._lastFrameTimeMs=78;G.MINIMAP_W=90;G.MINIMAP_H=65;
  G.document.createElement=function(){return{};};
  G.initAmbientParticles=function(){G.ambientParticles=[{x:Math.random(),alpha:0}];};
  G.updateAmbientParticles=function(dt){G.ambientParticles[0].alpha=Math.random();};
  G.initMinimap=function(){G.exploredCells=new Uint8Array([1,1,0]);G.minimapCanvas={canonical:true};G.minimapDirty=true;};
  G.updateLightGrid=function(){G._lightGrid[0]=Date.now()%1009;G._lightGridLastScale=0.9;G._surfaceFloorLightScale=0.8;};
  var originalAmbient=G.ambientParticles,originalExplored=G.exploredCells,originalMap=G.minimapCanvas,originalFog=G.drawMinimap._fogCanvas,originalLight=G._lightGrid;
  G.caveProfilePrepareInputs(job);
  var firstParticles=JSON.stringify(G.ambientParticles),firstLighting=G._lightGrid[0];
  check('canonical setup preserves live arrays by using temporary references',G.ambientParticles!==originalAmbient && G.exploredCells!==originalExplored && G.minimapCanvas!==originalMap && G.drawMinimap._fogCanvas!==originalFog && G._lightGrid!==originalLight);
  check('canonical setup retains particles and map instead of hiding quality features',G.ambientParticles.length===1 && G.exploredCells.length===3 && G.drawMinimap._fogCanvas.width===90 && G.drawMinimap._fogCanvas.height===65);
  check('canonical lighting forces a frozen-time update on its own buffer',firstLighting===job.frozenTime%1009 && G._lightGridFrameCount===4 && originalLight[0]!==firstLighting);
  check('canonical surface lighting shares immutable visibility and updates only its scalar',G._surfaceFloorLightBake===surfaceBake && G._surfaceFloorLightScale===0.8 && surfaceBake[0]===Math.fround(0.2));
  check('canonical setup restores native random and clock before yielding',Date.now===oldDate && Math.random===oldRandom);
  G.caveProfileRestoreInputs(job);
  check('profile teardown restores exact original world references',G.ambientParticles===originalAmbient && G.exploredCells===originalExplored && G.minimapCanvas===originalMap && G.drawMinimap._fogCanvas===originalFog && G._lightGrid===originalLight);
  check('profile teardown restores map lighting and FPS metadata',G.minimapDirty===false && G._lastExploredUpdate===123 && G._lightGridLastScale===0.3 && G._lightGridLastCamGX===7 && G._lightGridFrameCount===21 && G.settings.showFPS===true && G._fpsSmooth===42 && G._lastFrameTimeMs===78);
  check('profile teardown restores surface-light scalar and preserves baked references',G._surfaceFloorLightScale===0.4 && G._surfaceFloorLightBake===surfaceBake && G._surfaceFloorLightStats===surfaceStats && G._surfaceFloorLightMesh===G.floorMesh);
  G.caveProfilePrepareInputs(job);
  check('two profile setups produce identical particle and light inputs',JSON.stringify(G.ambientParticles)===firstParticles && G._lightGrid[0]===firstLighting);
  G.caveProfileRestoreInputs(job);
  var oldInit=G.initAmbientParticles;G.initAmbientParticles=function(){G.ambientParticles=[{temporary:true}];throw Error('setup failed');};
  failed=false;try{G.caveProfilePrepareInputs(job);}catch(e){failed=e.message==='setup failed';}
  G.caveProfileRestoreInputs(job);G.initAmbientParticles=oldInit;
  check('failed setup still restores changed arrays and native globals',failed && G.ambientParticles===originalAmbient && Date.now===oldDate && Math.random===oldRandom);
  G.caveProfilePrepareInputs(job);var newAmbient=[{newWorld:true}];G.floorMesh={id:'new'};G.ambientParticles=newAmbient;
  var newSurface=new Float32Array([0.9]);G._surfaceFloorLightBake=newSurface;G._surfaceFloorLightMesh=G.floorMesh;G._surfaceFloorLightScale=0.7;
  G.caveProfileRestoreInputs(job);
  check('cancel after world regeneration never restores old world arrays',G.ambientParticles===newAmbient);
  check('cancel after world regeneration preserves new surface lighting',G._surfaceFloorLightBake===newSurface && G._surfaceFloorLightMesh===G.floorMesh && G._surfaceFloorLightScale===0.7);
  __out('BROWSER_PROFILE_RESULT PASS '+checked);
}());
undefined;
