// Reuse the shipping browser-API host, then exercise the real studio and game.
(function () {
  var G=(0,eval)('this'), output=(__engine==='node'||__engine==='deno')?console.log.bind(console):__out, checked=0;
  var host=slurp('tools/game/tests/cave_occlusion_integration.js');
  var end=host.indexOf('  function check(name, okay) {');
  if(end<0)throw Error('shipping game host boundary missing');
  var bootstrap=host.slice(0,end),listenerStub='G.addEventListener = G.removeEventListener = noop;';
  if(bootstrap.indexOf(listenerStub)<0)throw Error('shipping window event host boundary missing');
  bootstrap=bootstrap.replace(listenerStub,'G.__studioWindowEvents={}; G.addEventListener=function(type,listener){(G.__studioWindowEvents[type]||(G.__studioWindowEvents[type]=[])).push(listener);}; G.removeEventListener=noop;');
  (0,eval)(bootstrap+'G.__studioErrors=errors; }());');
  G.document.fullscreenElement=G.document.webkitFullscreenElement=G.document.mozFullScreenElement=G.document.msFullscreenElement=null;
  if(typeof G.startCastingStudio!=='function')(0,eval)(slurp('assets/games/src/20-casting-preview.js'));
  function check(name,okay){if(!okay)throw Error(name);checked++;output('PASS '+name);}
  G._caveTestSeedOverride=12345;G._caveTestKindOverride='descending';
  G.CAVE_TEST_MODE=G.ENDLESS_MODE=G.running=true;G.gameOverState=false;G.terrain='plains';
  Object.keys(G.caveTestFlags).forEach(function(key){G.caveTestFlags[key]=false;});
  G.resetEndlessMode();G.MODE3D=true;G.overviewActive=false;G.USE_MOUSE=true;G.USE_GAMEPAD=false;
  G.settings.dayNight=true;G.dayTime=0.5;G.daySpeed=0;
  G.previewCaveView('mouth');
  check('studio defaults to the articulated anatomy proof, not rejected flat art',G._castingStudioMode==='hand');
  G._castingStudioMode='casting';
  var baseline={pos:G.pos,cam:G.cam,mana:G.mana,equipment:G.equipment,stats:G.stats,spells:G.spells,
    projectiles:G.projectiles,pending:G.pendingMissileCasts,reservation:G.spellCastReservationSerial,impacts:G.impacts,enemies:G.enemies,light:G._lightGrid,
    explored:G.exploredCells,minimap:G.minimapCanvas,pose:G._castingPoseState,day:G.dayTime,settings:G.settings,
    surfaceBake:G._surfaceFloorLightBake,surfaceMesh:G._surfaceFloorLightMesh,surfaceScale:G._surfaceFloorLightScale,surfaceStats:G._surfaceFloorLightStats};
  var job=G.startCastingStudio();
  check('studio uses a real clear lane in the existing seeded world',job.target.distance>=96&&job.target.distance<=220&&job.mesh===G.floorMesh);
  check('studio pauses ordinary loop without replacing player state',!G.running&&G.pos===baseline.pos&&G.cam===baseline.cam);
  check('studio owns independent combat and appearance state',job.live.equipment!==baseline.equipment&&job.live.stats!==baseline.stats&&job.live.enemies!==baseline.enemies&&job.live._castingPoseState!==baseline.pose);
  check('studio shares immutable terrain-light bake without changing live scale',job.live._surfaceFloorLightBake===baseline.surfaceBake&&G._surfaceFloorLightScale===baseline.surfaceScale&&G._surfaceFloorLightMesh===baseline.surfaceMesh);
  G.castingStudioAdvance(job,600);
  check('practice request enters production windup without an early projectile',job.requested&&!job.released&&job.live.projectiles.length===0&&job.live.pendingMissileCasts.length===1);
  check('pending practice cast never replaces the real queue or reservation serial',G.pendingMissileCasts===baseline.pending&&job.live.pendingMissileCasts!==baseline.pending&&G.spellCastReservationSerial===baseline.reservation);
  G.castingStudioAdvance(job,715);
  check('gather phase remains pending before the real release time',!job.released&&job.live.projectiles.length===0);
  G.castingStudioAdvance(job,1400);
  check('actual missile releases after requested 120 ms windup',Math.abs(job.requestAt-600)<0.001&&job.releaseAt>=720&&job.releaseAt<=720+G.CASTING_STUDIO_STEP_MS&&job.released);
  check('actual projectile cylinder collision damages practice target',job.hitAt>720&&job.hitAt<1400&&job.live.stats.totalDamageDone===1&&job.live.enemies[0].health===999);
  check('real mana cost remains in isolated practice state',job.live.mana===G.MANA_MAX-G.spells.missile.manaCost&&G.mana===baseline.mana);
  check('cast and hit do not alter actual arrays or stats',G.projectiles===baseline.projectiles&&G.pendingMissileCasts===baseline.pending&&G.impacts===baseline.impacts&&G.enemies===baseline.enemies&&G.stats===baseline.stats);
  var damage=job.live.stats.totalDamageDone, oldDate=Date.now, oldRandom=Math.random, caught=false;
  try{G.castingStudioScoped(job,function(){G.mana=7;G.projectiles=[];throw Error('deliberate draw failure');});}catch(e){caught=e.message==='deliberate draw failure';}
  check('exception restores global references and clock immediately',caught&&G.mana===baseline.mana&&G.projectiles===baseline.projectiles&&Date.now===oldDate&&Math.random===oldRandom);
  check('isolated state survives scope exit for next frame',job.live.mana===7&&job.live.stats.totalDamageDone===damage);
  G.setCastingStudioLight('dusk');
  check('dusk changes only studio lighting',job.live.dayTime===0.78&&G.dayTime===baseline.day&&G._lightGrid===baseline.light);
  check('dusk isolates exterior-light scalar while retaining same visibility bake',G._surfaceFloorLightScale===baseline.surfaceScale&&G._surfaceFloorLightBake===baseline.surfaceBake&&job.live._surfaceFloorLightBake===baseline.surfaceBake&&job.live._surfaceFloorLightScale!==baseline.surfaceScale);
  var beforeErrors=G.__studioErrors.length;
  G.castingStudioAdvance(job,1000);G.castingStudioDraw(job);
  check('actual full render reports no swallowed stage errors',G.__studioErrors.length===beforeErrors);
  check('draw restores pose settings and minimap references',G.cam===baseline.cam&&G.pos===baseline.pos&&G.settings===baseline.settings&&G.exploredCells===baseline.explored&&G.minimapCanvas===baseline.minimap&&G._castingPoseState===baseline.pose);
  caught=false;
  try{G.castingStudioScoped(job,function(){G._surfaceFloorLightScale=77;throw Error('lighting scope failure');});}catch(e){caught=e.message==='lighting scope failure';}
  check('failed studio draw restores surface-light state immediately',caught&&G._surfaceFloorLightScale===baseline.surfaceScale&&G._surfaceFloorLightBake===baseline.surfaceBake&&G._surfaceFloorLightMesh===baseline.surfaceMesh&&G._surfaceFloorLightStats===baseline.surfaceStats);
  G.setCastingStudioArt(false);
  check('A/B resets same pose and physics timeline',job.time===0&&!job.released&&!job.requested&&job.live.pendingMissileCasts.length===0&&job.live.CASTING_ART_ENABLED===false&&job.live.pos.x===baseline.pos.x&&job.live.pos.y===baseline.pos.y);
  G.castingStudioAdvance(job,1400);
  check('original visual path produces same real hit damage',job.live.stats.totalDamageDone===damage&&job.live.enemies[0].health===999);
  G.stopCastingStudio('test complete');
  check('stop restores original simulation and equipment',G._castingStudio===null&&G.running&&G.equipment===baseline.equipment&&G.spells===baseline.spells&&G.mana===baseline.mana);
  var cancelled=G.startCastingStudio(),resumes=0,cancels=0,oldCancel=G.cancelAnimationFrame;
  cancelled.profile=true;cancelled.raf=17;cancelled.resume=function(value){if(value===null)resumes++;};
  G.cancelAnimationFrame=function(id){if(id===17)cancels++;};
  G.stopCastingStudio('cancel requested');G.stopCastingStudio('cancel repeated');
  check('profile cancellation resolves pending frame exactly once',cancelled.stopped&&resumes===1&&cancels===1&&cancelled.resume===null&&cancelled.raf===0);
  check('async profile cancellation leaves cleanup to its owner',G._castingStudio===cancelled&&!G.running);
  cancelled.profile=false;G.castingStudioRestore(cancelled);G.cancelAnimationFrame=oldCancel;
  check('profile cleanup restores canvas and prior simulation once',G._castingStudio===null&&G.running&&G.canvas.width===cancelled.width&&G.canvas.height===cancelled.height);
  var yielding=G.startCastingStudio();yielding.profile=true;G.castingStudioYieldToControls();
  G.running=false;yielding.profile=false;G.castingStudioRestore(yielding);
  check('late profile cleanup cannot override an ordinary Stop action',G._castingStudio===null&&!G.running);
  var oldInit=G.initMinimap;G.initMinimap=function(){G.minimapCanvas={temporary:true};throw Error('deliberate setup failure');};
  caught=false;try{G.startCastingStudio();}catch(e){caught=e.message==='deliberate setup failure';}
  G.initMinimap=oldInit;
  check('preparation failure restores minimap and never claims simulation',caught&&G.minimapCanvas===baseline.minimap&&G._castingStudio===null&&!G.running&&Date.now===oldDate);
  var next=G.startCastingStudio(), replacement={test:'new-world'};
  G.floorMesh=replacement;G.running=false;
  G.stopCastingStudio('world replaced');
  check('late cleanup never resumes or overwrites a replacement world',G.floorMesh===replacement&&!G.running&&G._castingStudio===null);
  G.floorMesh=next.mesh;
  var oldGrid=G.grid;G.grid=new Uint8Array(G.grid.length);G.grid.fill(1);var rejected=false;
  try{G.startCastingStudio();}catch(e){rejected=e.message.indexOf('no clear practice lane')>=0;}
  check('blocked lane refuses demonstration rather than fabricating a hit',rejected&&G._castingStudio===null&&!G.running);
  G.grid=oldGrid;
  var oldRecorder=G.MediaRecorder,oldCapture=G.canvas.captureStream,tracksStopped=0,recorderStopped=0,captures=0;
  function FakeRecorder(){this.state='inactive';}
  FakeRecorder.isTypeSupported=function(type){return type==='video/webm;codecs=vp9';};
  FakeRecorder.prototype.start=function(){this.state='recording';};
  FakeRecorder.prototype.stop=function(){this.state='inactive';recorderStopped++;if(this.onstop)this.onstop();};
  G.MediaRecorder=FakeRecorder;
  G.canvas.captureStream=function(fps){captures++;check('video capture requests 30 fps without changing canvas size',fps===30&&this.width===360&&this.height===240);return{getTracks:function(){return[{stop:function(){tracksStopped++;}}];}};};
  G.recordCastingStudioCycle();var recordingJob=G._castingStudio,recording=recordingJob.recording;
  check('recording uses current appearance and light in export filename',recording.filename==='casting-original-dusk-360x240.webm'&&recording.recorder.state==='recording');
  G.recordCastingStudioCycle();
  check('recording cannot start a competing recorder',captures===1);
  G.stopCastingStudio('cancel partial capture');
  check('cancelled capture stops recorder and video track before restoration',recording.discard&&tracksStopped===1&&recorderStopped===1&&G._castingStudio===null);
  var exclusive=G.startCastingStudio();exclusive.profile=true;G.recordCastingStudioCycle();
  check('profile and video recording are mutually exclusive',captures===1&&!exclusive.recording);
  exclusive.profile=false;G.stopCastingStudio();
  G.MediaRecorder=undefined;var previousStudio=G._castingStudio;G.recordCastingStudioCycle();
  check('unsupported recorder does not start or change simulation',G._castingStudio===previousStudio&&captures===1);
  G.MediaRecorder=oldRecorder;G.canvas.captureStream=oldCapture;
  G.setCastingStudioMode('hand');
  var rigBaseline={preview:G.HAND_RIG_PREVIEW,time:G.HAND_RIG_TIME_MS,yaw:G.HAND_RIG_VIEW_YAW,grip:G.HAND_RIG_GRIP,style:G.HAND_RIG_STYLE};
  var savedCast=G.castCurrentSpell,savedProjectiles=G.updateProjectiles,savedEffects=G.tickEffects,combatCalls=0;
  G.castCurrentSpell=G.updateProjectiles=G.tickEffects=function(){combatCalls++;throw Error('anatomy study entered combat');};
  var hand=G.startCastingStudio();
  check('hand study requires no target or firing lane',hand.mode==='hand'&&hand.target===null&&hand.live.enemies.length===0&&G.castingStudioCycleMs(hand)===2800);
  check('default hand study is paused in handle grip with synchronized selector',!hand.playing&&hand.time===0&&hand.grip==='handle'&&hand.live.HAND_RIG_GRIP==='handle'&&G.document.getElementById('castingStudioGrip').value==='handle');
  check('rig state is isolated and rejected cutout stays disabled',hand.live.HAND_RIG_PREVIEW===true&&hand.live.CASTING_ART_ENABLED===false&&G.HAND_RIG_PREVIEW===rigBaseline.preview);
  G.setCastingStudioHandGrip('reach');
  G.scrubCastingStudio(780);
  check('explicit reach gather scrubs exact anatomy timeline without casting',hand.grip==='reach'&&hand.time===780&&hand.live.HAND_RIG_TIME_MS===780&&G.handStudioPhase(hand.time)==='Gather'&&combatCalls===0);
  check('gather scrubbing synchronizes range and named pose immediately',G.document.getElementById('castingStudioTime').value==='780'&&G.document.getElementById('castingStudioPhase').value==='780');
  var panel=G.document.getElementById('castingStudioPanel'),oldContains=panel.contains;
  panel.contains=function(node){return !!(node&&node.studioControl);};
  function event(type,target){return{type:type,target:target,cancelable:true,prevented:0,stopped:0,
    preventDefault:function(){this.prevented++;},stopImmediatePropagation:function(){this.stopped++;}};}
  var focus=event('click',G.canvas);hand.fullscreenPending=true;
  G.castingStudioControlEvent(focus);
  check('canvas focus during pending inspection never cancels studio',G._castingStudio===hand&&!hand.stopped&&hand.time===780);
  var press=event('pointerdown',G.canvas);G.castingStudioCanvasInput(press);
  check('canvas pointer press is consumed before gameplay handlers',press.prevented===1&&press.stopped===1&&hand.canvasPointerActive);
  var release=event('pointerup',{tagName:'BODY'});G.castingStudioCanvasInput(release);
  check('pointer release outside canvas is consumed and clears capture',release.prevented===1&&release.stopped===1&&!hand.canvasPointerActive);
  var click=event('click',G.canvas),doubleClick=event('dblclick',G.canvas);
  G.castingStudioCanvasInput(click);G.castingStudioCanvasInput(doubleClick);
  check('canvas clicks cannot reach game cast or fullscreen toggles',click.stopped===1&&doubleClick.stopped===1&&G._castingStudio===hand&&!hand.stopped&&combatCalls===0);
  var poseControl={tagName:'SELECT',id:'castingStudioPhase',studioControl:true};
  var poseLabel={tagName:'LABEL',control:poseControl,studioControl:true};
  G.castingStudioControlEvent(event('click',poseLabel));G.castingStudioControlEvent(event('change',poseControl));
  check('internal label and select event sequence preserves pending inspection',G._castingStudio===hand&&!hand.stopped&&hand.fullscreenPending&&hand.time===780);
  hand.fullscreenPending=false;
  var oldYield=G.castingStudioYieldToControls,yields=0;G.castingStudioYieldToControls=function(){yields++;};
  G.castingStudioControlEvent(event('click',{tagName:'BODY'}));
  G.castingStudioControlEvent(event('click',{tagName:'LABEL',control:null}));
  check('background and unrelated label clicks do not count as game controls',yields===0);
  var gameButton={tagName:'BUTTON',id:'btnStop'},gameText={tagName:'SPAN',parentElement:gameButton};
  G.castingStudioControlEvent(event('click',gameText));
  check('actual game button descendants still yield to their control',yields===1&&G.castingStudioControlTarget(gameText)===gameButton);
  G.castingStudioYieldToControls=oldYield;panel.contains=oldContains;
  G.scrubCastingStudio(1220);
  check('release pose retains empty projectiles and unchanged mana',hand.live.projectiles.length===0&&hand.live.pendingMissileCasts.length===0&&hand.live.mana===G.MANA_MAX&&G.handStudioPhase(hand.time)==='Release');
  G.setCastingStudioHandView(Math.PI);
  check('back inspection changes only the owned hand yaw',hand.live.HAND_RIG_VIEW_YAW===Math.PI&&G.HAND_RIG_VIEW_YAW===rigBaseline.yaw&&G.HAND_RIG_TIME_MS===rigBaseline.time);
  G.setCastingStudioHandView('palm');
  var palmScope=false;G.castingStudioScoped(hand,function(){palmScope=G.HAND_RIG_VIEW_YAW==='palm';});
  check('palm study preserves its scoped sentinel and restores player yaw without resizing',palmScope&&hand.yaw==='palm'&&hand.live.HAND_RIG_VIEW_YAW==='palm'&&G.HAND_RIG_VIEW_YAW===rigBaseline.yaw&&G.canvas.width===360&&G.canvas.height===240&&combatCalls===0);
  var restingEquipment=hand.live.equipment;
  hand.playing=true;G.setCastingStudioHandGrip('handle');
  check('handle grip selection stops the flourish and returns to rest',!hand.playing&&hand.time===0&&hand.live.HAND_RIG_GRIP==='handle'&&G.document.getElementById('castingStudioTime').value==='0');
  G.setCastingStudioHandGrip('cradle');
  check('cradle is scoped shape data, not an equipped item',hand.live.HAND_RIG_GRIP==='cradle'&&hand.live.equipment===restingEquipment&&G.equipment===baseline.equipment&&G.HAND_RIG_GRIP===rigBaseline.grip);
  G.setCastingStudioHandGrip('invalid');
  check('invalid resting template safely falls back to handle',hand.grip==='handle'&&hand.live.HAND_RIG_GRIP==='handle'&&G.document.getElementById('castingStudioGrip').value==='handle');
  G.setCastingStudioHandGrip('reach');
  G.setCastingStudioArt(false);
  check('original hand baseline never enables rejected flat study',!hand.live.HAND_RIG_PREVIEW&&!hand.live.CASTING_ART_ENABLED&&G.document.getElementById('castingStudioTime').value==='0');
  hand.playing=true;G.setCastingStudioArt(true);
  check('selecting articulated hand never auto-plays the casting flourish',!hand.playing&&hand.time===0&&combatCalls===0);
  var oldRaf=G.requestAnimationFrame,frames=[];
  G.requestAnimationFrame=function(fn){frames.push(fn);return frames.length;};
  G.playCastingStudio();frames.shift()(0);frames.shift()(40);
  check('hand playback advances at quarter wall-clock speed',Math.abs(hand.time-10)<0.000001&&combatCalls===0);
  G.pauseCastingStudio();frames=[];
  G.MediaRecorder=FakeRecorder;
  G.canvas.captureStream=function(){return{getTracks:function(){return[{stop:function(){tracksStopped++;}}];}};};
  G.recordCastingStudioCycle();var handRecording=hand.recording;
  check('hand recording includes selected style and independent resting template',handRecording.visualStudy&&handRecording.filename==='hand-motion-articulated-arcane-reach-dusk-360x240.webm');
  hand.time=2799;frames.shift()(0);frames.shift()(40);
  check('anatomy recording completes with no fabricated cast or hit',!hand.recording&&!handRecording.discard&&!hand.playing&&hand.hitAt===null&&combatCalls===0);
  G.requestAnimationFrame=oldRaf;G.MediaRecorder=oldRecorder;G.canvas.captureStream=oldCapture;
  hand.inspectionFullscreen=true;G.castingStudioFullscreenChanged();
  check('leaving inspection restores real rig state even after palm study',G._castingStudio===null&&G.HAND_RIG_PREVIEW===rigBaseline.preview&&G.HAND_RIG_TIME_MS===rigBaseline.time&&G.HAND_RIG_VIEW_YAW===rigBaseline.yaw&&G.HAND_RIG_GRIP===rigBaseline.grip&&G.HAND_RIG_STYLE===rigBaseline.style);
  G.setCastingStudioArt(true);
  check('opening articulated preview draws a resting hand without starting animation',G._castingStudio!==null&&!G._castingStudio.playing&&G._castingStudio.time===0&&G._castingStudio.live.HAND_RIG_GRIP==='reach');
  G.stopCastingStudio('resting proof complete');
  var preferenceBefore=G.getSelectedCastingStyle(),pendingBefore=G.pendingSettings;
  G.pendingSettings=Object.assign({},G.settings);
  var oldStudioDraw=G.castingStudioDraw,styleDraws=0,styleEvents=0;
  G.castingStudioDraw=function(value){styleDraws++;return oldStudioDraw(value);};
  var removeStyleObserver=G.onCastingStyleChange(function(){styleEvents++;});
  G.setCastingStudioStyle('finger_guns');
  var styled=G._castingStudio;
  check('selecting Finger Guns opens a paused ready proof with one draw',styled&&styled.style==='finger_guns'&&styled.time===0&&!styled.playing&&styleDraws===1&&styleEvents===1);
  check('style choice is present in scoped rig and synchronized control',styled.live.HAND_RIG_STYLE==='finger_guns'&&styled.live.settings.castingStyle==='finger_guns'&&G.document.getElementById('castingStudioStyle').value==='finger_guns');
  check('deliberate preference survives drawing while temporary rig style is restored',G.getSelectedCastingStyle()==='finger_guns'&&G.settings===baseline.settings&&G.settings.castingStyle==='finger_guns'&&G.pendingSettings.castingStyle==='finger_guns'&&G.HAND_RIG_STYLE===rigBaseline.style);
  G.setCastingStudioHandGrip('handle');G.scrubCastingStudio(1220);styled.playing=true;
  var styledEquipment=styled.live.equipment;
  G.setCastingStudioStyle('arcane');
  check('changing style pauses at ready but preserves independent handle contract',styled.style==='arcane'&&styled.time===0&&!styled.playing&&styled.grip==='handle'&&styled.live.HAND_RIG_GRIP==='handle'&&styled.live.equipment===styledEquipment&&combatCalls===0);
  check('style selection never changes actual equipment spell or combat state',G.equipment===baseline.equipment&&G.spells===baseline.spells&&G.stats===baseline.stats&&G.pendingMissileCasts===baseline.pending&&G.mana===baseline.mana);
  G.scrubCastingStudio(780);styled.playing=true;
  var externalDraws=styleDraws;
  G.setSelectedCastingStyle('finger_guns');
  check('external player style change refreshes active proof exactly once at rest',G._castingStudio===styled&&styled.style==='finger_guns'&&styled.live.HAND_RIG_STYLE==='finger_guns'&&styled.time===0&&!styled.playing&&styleDraws===externalDraws+1);
  var beforeUnchangedEvents=styleEvents;G.setSelectedCastingStyle('finger_guns');
  check('unchanged external preference cannot recursively restart the proof',styleEvents===beforeUnchangedEvents&&styleDraws===externalDraws+1);
  G.stopCastingStudio('style proof complete');
  check('closing studio preserves chosen preference but restores all real rig state',G._castingStudio===null&&G.getSelectedCastingStyle()==='finger_guns'&&G.HAND_RIG_STYLE===rigBaseline.style&&G.HAND_RIG_GRIP===rigBaseline.grip&&G.HAND_RIG_PREVIEW===rigBaseline.preview);
  var resumedStyle=G.startCastingStudio();
  check('new proof starts with saved style and independent resting template',resumedStyle.style==='finger_guns'&&resumedStyle.live.HAND_RIG_STYLE==='finger_guns'&&resumedStyle.grip==='handle'&&!resumedStyle.playing);
  G.stopCastingStudio('style reopen complete');
  var inactiveRunning=G.running,inactiveDraws=styleDraws;
  G.setSelectedCastingStyle('arcane');
  check('external style selection without a proof updates control without opening one',G._castingStudio===null&&G.running===inactiveRunning&&styleDraws===inactiveDraws&&G.document.getElementById('castingStudioStyle').value==='arcane');
  G.setCastingStudioStyle('missing-style');
  check('invalid studio style safely uses the registry default without entering combat',G._castingStudio.style==='arcane'&&G.getSelectedCastingStyle()==='arcane'&&combatCalls===0);
  G.stopCastingStudio('invalid style proof complete');removeStyleObserver();
  var pagehide=G.__studioWindowEvents.pagehide.filter(function(listener){return listener.toString().indexOf('castingStudioRevokeVideo')>=0;})[0];
  if(!pagehide)throw Error('shipping studio pagehide listener missing');
  var cachedStyleSubscription=G._castingStudioStyleUnsubscribe,oldRevoke=G.castingStudioRevokeVideo,revokes=0;
  G.castingStudioRevokeVideo=function(){revokes++;};G.startCastingStudio();
  pagehide({persisted:true});
  check('cached pagehide stops preview and releases video without dropping style subscription',G._castingStudio===null&&revokes===1&&G._castingStudioStyleUnsubscribe===cachedStyleSubscription);
  G.setSelectedCastingStyle('finger_guns');var cachedProof=G.startCastingStudio();G.setSelectedCastingStyle('arcane');
  check('cached page return keeps player and studio style choices synchronized',cachedProof.style==='arcane'&&cachedProof.live.HAND_RIG_STYLE==='arcane'&&G.document.getElementById('castingStudioStyle').value==='arcane');
  pagehide({persisted:false});
  check('real page unload releases preview video and style listener exactly once',G._castingStudio===null&&revokes===2&&G._castingStudioStyleUnsubscribe===null);
  G.castingStudioRevokeVideo=oldRevoke;
  G.castingStudioDraw=oldStudioDraw;G.setSelectedCastingStyle(preferenceBefore);G.pendingSettings=pendingBefore;
  G.castCurrentSpell=savedCast;G.updateProjectiles=savedProjectiles;G.tickEffects=savedEffects;
  output('CASTING_STUDIO_RESULT PASS '+checked);
}());
undefined;
