#!/usr/bin/env python3
"""Generate/check exact gzip web assets using only Python's standard library.

No JavaScript transformation is performed. --check validates the committed
representation, including decompression, so differing host zlib versions never
cause a build to rewrite the source tree or reject an otherwise valid asset.
"""
import argparse
import binascii
import hashlib
from pathlib import Path
import re
import struct
import zlib

HERE = Path(__file__).resolve().parent
HEADER = HERE.parent / 'WebAssets_Generated.h'
SOURCE = HERE / 'espnow-core.js'
URI = '/assets/espnow-core.js'


def sha(data):
    return hashlib.sha256(data).hexdigest()


def gzip_exact(data):
    compressor = zlib.compressobj(9, zlib.DEFLATED, -15)
    payload = compressor.compress(data) + compressor.flush()
    # Fixed header: no name, timestamp, platform, or environment-dependent data.
    return (b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\xff' + payload
            + struct.pack('<II', binascii.crc32(data) & 0xffffffff, len(data)))


def render(raw, packed):
    lines = ['  ' + ', '.join('0x%02x' % x for x in packed[i:i+16]) + ','
             for i in range(0, len(packed), 16)]
    return ('// Generated by web_assets/generate.py; do not edit.\n'
            '// JavaScript remains byte-exact, gzip only.\n'
            '#pragma once\n#include <cstddef>\n#include <cstdint>\n\n'
            'namespace hw1 { namespace web_assets {\n'
            '// Source SHA256: ' + sha(raw) + '\n'
            '// Gzip SHA256: ' + sha(packed) + '\n'
            '// Source bytes: ' + str(len(raw)) + '\n'
            'static constexpr char kEspNowCoreUri[] = "' + URI + '";\n'
            'static const uint8_t kEspNowCoreGzip[] = {\n'
            + '\n'.join(lines) + '\n};\n'
            'static constexpr size_t kEspNowCoreGzipSize = sizeof(kEspNowCoreGzip);\n'
            '} } // namespace hw1::web_assets\n')


def check(header=HEADER, source=SOURCE):
    raw = source.read_bytes()
    text = header.read_text()
    match = re.search(r'kEspNowCoreGzip\[\] = \{\n(.*?)\n\};', text, re.S)
    if not match:
        raise ValueError('Missing or malformed generated asset array')
    tokens = re.findall(r'0x([0-9a-f]{2})', match[1])
    packed = bytes(int(x, 16) for x in tokens)
    if re.sub(r'0x[0-9a-f]{2}|[\s,]', '', match[1]):
        raise ValueError('Unexpected generated asset array contents')
    decoder = zlib.decompressobj(31)
    restored = decoder.decompress(packed, len(raw) + 1)
    if (restored != raw or not decoder.eof or decoder.unused_data
            or decoder.unconsumed_tail):
        raise ValueError('Compressed web asset does not match editable JavaScript')
    if packed[:10] != b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\xff':
        raise ValueError('Gzip asset contains non-deterministic header fields')
    if text != render(raw, packed):
        raise ValueError('Generated web asset metadata/header differs from content')
    return len(raw), len(packed), sha(raw)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        if not args.check:
            raw = SOURCE.read_bytes()
            HEADER.write_text(render(raw, gzip_exact(raw)))
        raw, packed, identity = check()
    except (OSError, ValueError, zlib.error) as error:
        parser.exit(1, 'Web asset check failed: %s\nRun python3 %s\n' % (error, Path(__file__).name))
    print('ESP-NOW asset: %d -> %d bytes; source SHA256 %s' % (raw, packed, identity))


if __name__ == '__main__':
    main()
